### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-shaarli#5]
After logging in:

```
/**
     * Move old configuration in PHP to the new config system in JSON format.
     *
     * Will rename 'config.php' into 'config.save.php' and create 'config.json.php'.
     * It will also convert legacy setting keys to the new ones.
     */
Method [ <user> public method updateMethodConfigToJson ] {
  @@ /srv/http/sites/s20cff847410ebbd07ac0b06c5d2d33fbdd247068/shaarli/application/Updater.php 156 - 195
}

An error occurred while running the update MissingFieldConfigException: Configuration value is required for general.header_link in /srv/http/sites/s20cff847410ebbd07ac0b06c5d2d33fbdd247068/shaarli/application/config/ConfigManager.php:201
Stack trace:
#0 /srv/http/sites/s20cff847410ebbd07ac0b06c5d2d33fbdd247068/shaarli/application/Updater.php(189): ConfigManager->write(true)
#1 [internal function]: Updater->updateMethodConfigToJson()
#2 /srv/http/sites/s20cff847410ebbd07ac0b06c5d2d33fbdd247068/shaarli/application/Updater.php(86): ReflectionMethod->invoke(Object(Updater))
#3 /srv/http/sites/s20cff847410ebbd07ac0b06c5d2d33fbdd247068/shaarli/index.php(757): Updater->update()
#4 /srv/http/sites/s20cff847410ebbd07ac0b06c5d2d33fbdd247068/shaarli/index.php(2188): renderPage(Object(ConfigManager), Object(PluginManager))
#5 {main}
```

**Comment by jernst** [comment]
Need to update manifest (plugin directory missing) and the config file is all different.
